version: "2.1"
services:
  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo:3.6.8
    environment:
      - MONGO_INITDB_DATABASE=langdb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-data:/data/db
    ports:
      - "27017-27019:27017-27019"
    healthcheck:
      test: echo 'db.stats().ok' | mongo 127.0.0.1:27017 --quiet
      interval: 5s
      timeout: 5s
      retries: 12
    command: mongod --smallfiles

  api-server-quarkus:
    hostname: api-server-quarkus
    container_name: api-server-quarkus
    image: voteapp-api-quarkus:1.0.0-SNAPSHOT
    environment:
      MONGODB_HOSTNAME: mongodb
    ports:
      - "8000:8080"
    depends_on:
      mongodb:
        condition: service_healthy


